### PR TITLE
Several character parsers

### PR DESCRIPTION
**Pull request by jxv**
Here's some commits aimed to suffice some parsers mentioned in #2. Namely:
* newline
* crlf
* tab
* uppper
* lower
* letter
* alpha_num
* hex_digit
* oct_digit

### CODE REVIEW

**Comment by Marwes** [comment]
Thanks for the pull request!

I have a few thoughts on how to make it better before I merge it though.

If you could do a rebase to squash the at least commits where you merged that would be great (and maybe rebase on top of master if you feel like it to avoid the merge altogether).

Second, I missed doing this myself for the `satisfy` parser which is why I guess you missed it as well but when writing a function which creates a parser you should make sure that it has the same bounds as the parser impl so for all the char parser the stream should be `I: Stream<Item=char>`. Making sure that the bounds always match is easy to miss but it makes it so that compile errors are always caught as close to the source as possible.

Third is also something that I have been kind of sloppy but I am trying to fix. I find it cleaner if the real type of the parsers are hidden so that a user isn't exposed to the internals of the implementation. So for instance the newline parser should be written as follows.
```
impl_char_parser! { Newline(), Satisfy<I, fn (char) -> bool> }
///Parses a newline character
pub fn newline<I>() -> NewLine<I>
    where I: Stream<Item=char> {
    NewLine(satisfy(static_fn!((ch, char) -> bool { ch == '\n' })))
}
```
As a bonus, by using the macro it adds the `Ì: Stream<Item=char>` bound so that it isn't forgotten for the function.

**Comment by Marwes** [comment]
Made a pull request fixing the things I mentioned for the parsers that are there right now but I can hold of merging it until after this #13.

**Comment by jxv** [comment]
Go ahead and merge #13. I'm struggling with git right now. I'm going to nuke my repo and reclone yours then apply the proper changes as mentioned above.

**Comment by Marwes** [comment]
Yeah git can sadly be a bit difficult to work with. Look up the git rebase -i command, you can usually fix most problems in the branch with that, as long as no one else has cloned the branch.

**Comment by jxv** [comment]
Yeah, I spent some good minutes trying to follow along git rebase tutorials. I think I sluggishly got half way through, so I'll look more at it later.

**Comment by jxv** [comment]
Refer #14.

**Pull request closed without merging**
