### PR TITLE
Update from Rust's obsoleted closure syntax

### PR DESCRIPTION
**Pull request by jxv**
Maintaince PR, no features.

### CODE REVIEW

**Comment by Marwes** [comment]
Huh, are they removing the &mut/& specifiers? Thought they were necessary atleast in some cases since inferring it would be to much work. (And only they &mut specifier? Does it not work without any specifier?)

**Comment by Marwes** [comment]
Seems they are but for some reason |&:| still compiles but not |&mut:| I will pull this in locally and remove the specifier completely before merging

**Comment by jxv** [comment]
Yes, it fails with ```&mut``` using the latest nightly.

**Comment by Marwes** [comment]
Closed by 8889f120537ceaf233d0def185aca0e63817370d

**Comment by Marwes** [comment]
Did an amend on your commit since it seemed unnecessary to have two basically identical commits. Hopefully it should still work for you if you had work based on this (if nothing else the rebase should be simple)

**Pull request closed without merging**
